"""empty message

Revision ID: 32b4f0ea8abb
Revises: 
Create Date: 2021-03-29 13:20:09.225987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b4f0ea8abb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('activation', sa.Integer(), nullable=True),
    sa.Column('auth_status', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('b_code', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dollar_rate', sa.Integer(), nullable=True),
    sa.Column('sell_btc', sa.Integer(), nullable=True),
    sa.Column('sell_eth', sa.Integer(), nullable=True),
    sa.Column('btc_rate', sa.Integer(), nullable=True),
    sa.Column('eth_rate', sa.Integer(), nullable=True),
    sa.Column('eth_to_dollar', sa.String(length=100), nullable=True),
    sa.Column('debit_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('referral', sa.Integer(), nullable=True),
    sa.Column('btc_limit', sa.Integer(), nullable=True),
    sa.Column('local_limit', sa.Integer(), nullable=True),
    sa.Column('eth_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('pin', sa.Text(), nullable=True),
    sa.Column('dob', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('uid', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('activation', sa.Integer(), nullable=True),
    sa.Column('recovery_phone', sa.String(length=20), nullable=True),
    sa.Column('bank', sa.String(length=200), nullable=False),
    sa.Column('bank_account', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('notify', sa.Integer(), nullable=True),
    sa.Column('auth2fa', sa.Integer(), nullable=True),
    sa.Column('verify_me', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('activitieslogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('activities', sa.Text(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('os_name', sa.String(length=100), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=True),
    sa.Column('activities_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deposit_ref', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.String(length=200), nullable=False),
    sa.Column('charges', sa.String(length=200), nullable=False),
    sa.Column('pre_amount', sa.String(length=200), nullable=False),
    sa.Column('deposit_token', sa.Text(), nullable=False),
    sa.Column('deposit_status', sa.Integer(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('deposit_link', sa.Text(), nullable=True),
    sa.Column('per_cent', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposit')
    op.drop_table('activitieslogs')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('banks')
    op.drop_table('auth_codes')
    # ### end Alembic commands ###
